
name: CI

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XPOSED_BASE_TAG: base
  JELLYFIN_VERSION: '10.7.7'
  JELLYFIN_SOURCE_TAG: v10.7.7
  JELLYFIN_BUILD_PLATFORM: portable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/std4453/jellyfin-xposed
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            prefix=${{ env.JELLYFIN_VERSION }}-xp-

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache build result
        id: cache-build
        uses: actions/cache@v2
        with:
          # cache based on self sha instead of ref since a push and a tag
          # will trigger two workflows
          key: ${{ github.sha }}-${{ env.JELLYFIN_SOURCE_TAG }}-build
          path: ./artifacts/jellyfin-xposed.tar.gz

        # the following steps are based on current sha and produce
        # reproduciable results so they are skipped on cache hit

      - name: Setup git config
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          git config user.email "<>"
          git config user.name "runner"
      
      - name: Remove unnecessary files from history
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: >
          git filter-branch --tree-filter 
          'rm -rf ./README.md ./.gitignore ./github'
          --
          ${{ env.XPOSED_BASE_TAG }}..HEAD

      - name: Fetch Jellyfin upstream
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          git remote add jellyfin https://github.com/jellyfin/jellyfin-web.git
          git fetch jellyfin --tags

      - name: Rebase onto Jellyfin
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          git rebase --onto ${{ env.JELLYFIN_SOURCE_TAG }} ${{ env.XPOSED_BASE_TAG }} HEAD
      
      - name: Build Jellyfin web and rename tarball
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          SOURCE_DIR=. ARTIFACT_DIR=./artifacts ./deployment/build.${{ env.JELLYFIN_BUILD_PLATFORM }}
          mv ./artifacts/jellyfin-web_${{ env.JELLYFIN_VERSION }}_${{ env.JELLYFIN_BUILD_PLATFORM }}.tar.gz ./artifacts/jellyfin-xposed.tar.gz

        # the following steps might vary on ref so cannot be skipped

      - name: Untar Jellyfin tarball
        working-directory: ./artifacts
        run: tar xvf ./jellyfin-xposed.tar.gz
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./artifacts/jellyfin-web_${{ env.JELLYFIN_VERSION }}
          file: ./Dockerfile.Xposed
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Upload tarball to release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: ./artifacts/jellyfin-xposed.tar.gz
          name: ${{ env.JELLYFIN_VERSION }}-xp-${{ github.ref_name }}
