
name: CI

on:
  push:
    branches: [ 'main' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XPOSED_BASE_TAG: xposed-base
  JELLYFIN_VERSION: '10.7.7'
  JELLYFIN_SOURCE_TAG: v10.7.7
  JELLYFIN_BUILD_PLATFORM: portable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/std4453/jellyfin-xposed
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            prefix=${{ env.JELLYFIN_VERSION }}-xp-

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git config
        run: |
          git config user.email "<>"
          git config user.name "runner"

      - name: Fetch Jellyfin upstream
        run: |
          git remote add jellyfin https://github.com/jellyfin/jellyfin-web.git
          git fetch jellyfin --tags

      - name: Rebase onto Jellyfin
        run: |
          git checkout ${{ env.JELLYFIN_SOURCE_TAG }}
          git cherry-pick ${{ env.XPOSED_BASE_TAG }}..$GITHUB_SHA

      - name: Build Jellyfin web
        run: |
          SOURCE_DIR=. ARTIFACT_DIR=./artifacts ./deployment/build.${{ env.JELLYFIN_BUILD_PLATFORM }}

      - name: Untar Jellyfin tarball
        working-directory: ./artifacts
        run: tar xvf ./jellyfin-web_${{ env.JELLYFIN_VERSION }}_${{ env.JELLYFIN_BUILD_PLATFORM }}.tar.gz
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./artifacts/jellyfin-web_${{ env.JELLYFIN_VERSION }}
          file: ./Dockerfile.Xposed
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
